<?php
$title = 'О нас';
$this->headTitle($title);
?>
<div class="replace hide">
    <section class="promo section">
        <div class="container text-center">
            <h2 class="title">О нас</h2>
            <div class="intro">
                <p>Ваша идея требует <span class="highlight">нестандартных решений?</span></p>
                <p>Вашему бизнесу не подходят <span class="highlight">существующие CMS?</span></p>
                <p>Мы разработаем web-приложение, от которого вы <span class="highlight">не сможете отказаться</span></p>.
            </div>
        </div><!--//container-->
    </section><!--//promo-->
</div><!--//header-wrapper-->

<!-- ******Services Section****** -->
<section id="services" class="services section">
    <div class="container text-center">
        <h2 class="title">Услуги</h2>
        <div class="intro">
            <p>Мы предлагаем систему в которой:</p>
            <ul class="text-left">
                <li><span class="highlight">архитектура и функциональность</span> приложения разработана индивидуально для вас;</li>
                <li><span class="highlight">логика приложения</span> согласована с вашими бизнес-процессами;</li>
                <li><span class="highlight">структура базы данных</span> соответствует вашим требованиям;</li>
                <li><span class="highlight">корректное отображение</span> сайта на различных устройствах;</li>
                <li><span class="highlight">высоконагруженность и безопасность</span>.</li>
            </ul>
        </div>
        <div class="service-items row">
            <div class="item col-lg-3 col-md-6 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="header-box">
                        <span class="fs1" aria-hidden="true" data-icon="&#xe104;"></span>
                    </div><!--//header-->
                    <div class="desc">
                        <h3 class="sub-title">UX &amp; Frontend</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae diam magna. Curabitur nibh metus, ultricies sed aliquam euismod, scelerisque eu purus. In hac habitasse platea dictumst. Suspendisse tempus elit eget libero suscipit pulvinar.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-lg-3 col-md-6 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="header-box">
                        <span class="fs1" aria-hidden="true" data-icon="&#xe0ea;"></span>
                    </div><!--//header-->
                    <div class="desc">
                        <h3 class="sub-title">Backend &amp; Database</h3>
                        <p>Phasellus fermentum accumsan fermentum. Vestibulum elit sapien, consequat vitae auctor sit amet, elementum sed elit. Quisque ullamcorper quis augue sit amet porttitor. Maecenas ac dolor iaculis, dapibus.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-lg-3 col-md-6 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="header-box">
                        <span class="fs1" aria-hidden="true" data-icon="&#xe003;"></span>
                    </div><!--//header-->
                    <div class="desc">
                        <h3 class="sub-title">Hosting</h3>
                        <p>Cras mollis ex sed tortor finibus, a mattis risus rhoncus. Sed sodales et metus at sodales. Ut non dolor sollicitudin, venenatis mauris eget, fringilla enim. Pellentesque sed magna ante. Cras mollis tincidunt lectus vitae suscipit.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-lg-3 col-md-6 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="header-box">
                        <span class="fs1" aria-hidden="true" data-icon="&#xe028;"></span>
                    </div><!--//header-->
                    <div class="desc">
                        <h3 class="sub-title">Support</h3>
                        <p>Aliquam efficitur, lorem blandit dapibus viverra, erat turpis placerat lacus, quis hendrerit libero sem eget dui. Integer eu diam orci. Nullam sed dictum lorem. Quisque ut lacus non enim aliquam pretium sit amet id augue.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
        </div><!--//row-->
        <a class="btn btn-cta btn-cta-primary" href="<?= $this->url('contact'); ?>">Связаться</a>
    </div><!--//container-->
</section>

<!-- ******CTA Section****** -->
<section id="cta-section" class="cta-section section text-center home-cta-section">
    <div class="container">
        <h2 class="title">Хотите быстро связатся с нами?</h2>
        <p class="phone contact-info">
            <span class="intro">Вы в одном телефонном звонке от этого</span>
            <span class="info"><a href="tel:+380675623777">0675623777</a></span>
        </p><!--//phone-->
        <p class="email contact-info">
            <span class="intro">Вы так же можете отправить email</span>
            <span class="info"><a href="mailto:versover@gmail.com">versover@gmail.com</a></span>
        </p><!--//phone-->
    </div><!--//container-->
</section><!--//cta-section-->