<?php
$title = $this->translate('Контакты');
$this->headTitle($title);
?>
<div class="replace hide">
    <section class="promo section">
        <div class="container text-center">
            <h2 class="title"><?= $this->translate('Связь с нами'); ?></h2>
            <div>
                <p><?= $this->translate('Всегда на связи!'); ?></p>
                <p><?= $this->translate('Если вас интересует проект или хотите узнать больше о наших услугах. <span class="highlight">Мы будем рады вам!'); ?></span></p>
            </div>
        </div><!--//container-->
    </section><!--//promo-->
</div>

<!-- ******Contact Section****** -->
<section class="contact-section section">
    <div class="container">
        <h2 class="title text-center"><?= $this->translate('Начните проект сегодня'); ?></h2>
        <p class="intro text-center"><?= $this->translate('Если у вас есть предложение, вопрос - смело пишите нам - мы ответим Вам в ближайшее время!'); ?></p>
        <ul class="contact-info list-inline text-center">
            <li class="tel"><span class="fs1" aria-hidden="true" data-icon="&#x77;"></span><br /> <a href="tel:+380675623777">0675623777</a></li>
            <li class="email"><span class="fs1" aria-hidden="true" data-icon="&#xe010;"></span><br /> <a href="mailto:versoverteam@gmail.com">versoverteam@gmail.com</a></li>
            <li class="skype-icon"><span class="fs1" aria-hidden="true" data-icon="&#xe0a2;"></span><br /> <a href="skype:versover?chat">Versover</a></li>
        </ul>
        <form id="contact-form" class="contact-form form" method="post" action="<?= $this->url('contact', ['action' => 'send']); ?>">
            <div class="row text-center">
                <div class="contact-form-inner col-md-8 col-sm-12 col-xs-12 col-md-offset-2 col-sm-offset-0 xs-offset-0">
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-12 form-group">
                            <label class="sr-only" for="cname"><?= $this->translate('Ваше имя'); ?></label>
                            <input type="text" class="form-control" id="cname" name="name" placeholder="<?= $this->translate('Ваше имя'); ?>" minlength="2" required>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-group">
                            <label class="sr-only" for="cemail"><?= $this->translate('Ваш email'); ?></label>
                            <input type="email" class="form-control" id="cemail" name="email" placeholder="<?= $this->translate('Ваш email'); ?>" required>
                        </div>
                        <div class="col-md-12 col-sm-12 col-xs-12 form-group">
                            <label class="sr-only" for="csubject"><?= $this->translate('Тема'); ?></label>
                            <input type="text" class="form-control" id="csubject" name="subject" placeholder="<?= $this->translate('Тема'); ?>" required>
                        </div>
                        <div class="col-md-12 col-sm-12 col-xs-12 form-group">
                            <label class="sr-only" for="cmessage"><?= $this->translate('Ваше сообщение'); ?></label>
                            <textarea class="form-control" id="cmessage" name="message" placeholder="<?= $this->translate('Ваше сообщение'); ?>" rows="12" required></textarea>
                        </div>
                        <div class="col-md-12 col-sm-12 col-xs-12 form-group">
                            <button type="submit" class="btn btn-block btn-cta btn-cta-primary sbm-btn"><?= $this->translate('Отправить сообщение'); ?></button>
                        </div>
                    </div><!--//row-->
                </div>
            </div><!--//row-->
            <div id="form-messages"></div>
        </form><!--//contact-form-->
    </div><!--//container-->
</section><!--//contact-section-->