<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'Application\Module'                       => __DIR__ . '/Module.php',
    'Application\Controller\AboutController'   => __DIR__ . '/src/Application/Controller/AboutController.php',
    'Application\Controller\BlogController'    => __DIR__ . '/src/Application/Controller/BlogController.php',
    'Application\Controller\ContactController' => __DIR__ . '/src/Application/Controller/ContactController.php',
    'Application\Controller\IndexController'   => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Controller\WorkController'    => __DIR__ . '/src/Application/Controller/WorkController.php',
];
