<?php
$title = 'Blog';
$this->headTitle($title);
?>
<div class="replace hide">
    <section class="promo section">
        <div class="container text-center">
            <h2 class="title">Blog</h2>
            <p class="intro">Lorem ipsum dolor sit amet consectetuer adipiscing elit massa sociis natoque penatibus et magnis dis parturient montes</p>
        </div><!--//container-->
    </section><!--//promo-->
</div>

<!-- ******Blog list Section****** -->
<section id="blog-list" class="blog-list section">
    <div class="container">
        <article class="item">
            <div class="row">
                <h3 class="post-title col-md-10 col-sm-9 col-xs-12 col-md-push-2 col-sm-push-3 col-xs-push-0"><a href="#">DevStudio helps XYZ launch</a></h3>
                <div class="clearfix"></div>
                <div class="meta col-md-2 col-sm-3 col-xs-12 text-right">
                    <ul class="meta-list list-unstyled">
                        <li class="post-time post_date date updated">
                            <span class="date">18</span>
                            <span class="month">Feb</span>
                        </li>
                        <li class="post-author"><a href="#">James Lee</a></li>
                        <li class="post-comments-link">
                            Comments: <a href="##comment-area">5</a>
                        </li>
                    </ul><!--//meta-list-->
                </div><!--//meta-list-->
                <div class="content-wrapper col-md-10 col-sm-9 col-xs-12">
                    <figure class="figure">
                        <a href="#"><img class="img-responsive" src="/img/blog/blog-1.jpg" alt=""></a>
                    </figure>
                    <div class="content">
                        <div class="desc">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sodales dolor ut ligula faucibus, nec mattis nibh eleifend. Duis et enim at lacus pharetra mollis molestie nec magna. Maecenas tristique laoreet tristique. Ut pellentesque diam nec odio hendrerit euismod...</p>
                            <a class="read-more" href="#">Read more <i class="fa fa-long-arrow-right"></i></a>
                        </div><!--//desc-->
                    </div><!--//content-->
                </div><!--//content-wrapper-->
            </div><!--//row-->
        </article><!--//item-->
        <article class="item">
            <div class="row">
                <h3 class="post-title col-md-10 col-sm-9 col-xs-12 col-md-push-2 col-sm-push-3 col-xs-push-0"><a href="#">devAid - Free Bootstrap Theme</a></h3>
                <div class="clearfix"></div>
                <div class="meta col-md-2 col-sm-3 col-xs-12 text-right">
                    <ul class="meta-list list-unstyled">
                        <li class="post-time post_date date updated">
                            <span class="date">6</span>
                            <span class="month">Jan</span>
                        </li>
                        <li class="post-author"><a href="#">James Lee</a></li>
                        <li class="post-comments-link">
                            Comments: <a href="##comment-area">8</a>
                        </li>
                    </ul><!--//meta-list-->
                </div><!--//meta-list-->
                <div class="content-wrapper col-md-10 col-sm-9 col-xs-12">
                    <figure class="figure">
                        <a href="#"><img class="img-responsive" src="/img/blog/blog-2.jpg" alt=""></a>
                    </figure>
                    <div class="content">
                        <div class="desc">
                            <p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut et sagittis metus, in cursus nulla. Quisque quam eros, luctus at dolor eu, fermentum convallis diam. Donec consequat nulla quis ipsum suscipit convallis. Pellentesque id aliquet ante. <a href="http://themes.3rdwavemedia.com/website-templates/devaid-free-bootstrap-theme-developers/" target="_blank">Download now</a> fusce id sodales ligula. Fusce at erat rutrum nulla scelerisque consectetur et eget mauris...</p>
                            <a class="read-more" href="#">Read more <i class="fa fa-long-arrow-right"></i></a>
                        </div><!--//desc-->
                    </div><!--//content-->
                </div><!--//content-wrapper-->
            </div><!--//row-->
        </article><!--//item-->
        <article class="item">
            <div class="row">
                <h3 class="post-title col-md-10 col-sm-9 col-xs-12 col-md-push-2 col-sm-push-3 col-xs-push-0"><a href="#">DevStudio Team Lorem Ipsum</a></h3>
                <div class="clearfix"></div>
                <div class="meta col-md-2 col-sm-3 col-xs-12 text-right">
                    <ul class="meta-list list-unstyled">
                        <li class="post-time post_date date updated">
                            <span class="date">21</span>
                            <span class="month">Dec</span>
                        </li>
                        <li class="post-author"><a href="#">Vincent Fowler</a></li>
                        <li class="post-comments-link">
                            Comments: <a href="##comment-area">8</a>
                        </li>
                    </ul><!--//meta-list-->
                </div><!--//meta-list-->
                <div class="content-wrapper col-md-10 col-sm-9 col-xs-12">
                    <figure class="figure">
                        <a href="#"><img class="img-responsive" src="/img/blog/blog-3.jpg" alt=""></a>
                    </figure>
                    <div class="content">
                        <div class="desc">
                            <p>Aliquam quis nibh id lorem fringilla scelerisque. Etiam euismod lectus at arcu ultrices suscipit. Ut eu mi in lectus viverra scelerisque. Nulla non commodo est. Aenean id tristique est. Pellentesque hendrerit tortor nulla, dapibus consequat orci convallis vitae. Vivamus at odio fermentum justo...</p>
                            <a class="read-more" href="#">Read more <i class="fa fa-long-arrow-right"></i></a>
                        </div><!--//desc-->
                    </div><!--//content-->
                </div><!--//content-wrapper-->
            </div><!--//row-->
        </article><!--//item-->
        <article class="item">
            <div class="row">
                <h3 class="post-title col-md-10 col-sm-9 col-xs-12 col-md-push-2 col-sm-push-3 col-xs-push-0"><a href="#">Our Consectetur Adipiscing</a></h3>
                <div class="clearfix"></div>
                <div class="meta col-md-2 col-sm-3 col-xs-12 text-right">
                    <ul class="meta-list list-unstyled">
                        <li class="post-time post_date date updated">
                            <span class="date">17</span>
                            <span class="month">Nov</span>
                        </li>
                        <li class="post-author"><a href="#">Sara Valdez</a></li>
                        <li class="post-comments-link">
                            Comments: <a href="##comment-area">8</a>
                        </li>
                    </ul><!--//meta-list-->
                </div><!--//meta-list-->
                <div class="content-wrapper col-md-10 col-sm-9 col-xs-12">
                    <figure class="figure">
                        <a href="#"><img class="img-responsive" src="/img/blog/blog-4.jpg" alt=""></a>
                    </figure>
                    <div class="content">
                        <div class="desc">
                            <p>Aliquam quis nibh id lorem fringilla scelerisque. Etiam euismod lectus at arcu ultrices suscipit. Ut eu mi in lectus viverra scelerisque. Nulla non commodo est. Aenean id tristique est. Pellentesque hendrerit tortor nulla, dapibus consequat orci convallis vitae. Vivamus at odio fermentum justo...</p>
                            <a class="read-more" href="#">Read more <i class="fa fa-long-arrow-right"></i></a>
                        </div><!--//desc-->
                    </div><!--//content-->
                </div><!--//content-wrapper-->
            </div><!--//row-->
        </article><!--//item-->
        <article class="item">
            <div class="row">
                <h3 class="post-title col-md-10 col-sm-9 col-xs-12 col-md-push-2 col-sm-push-3 col-xs-push-0"><a href="#">UX Workshop</a></h3>
                <div class="clearfix"></div>
                <div class="meta col-md-2 col-sm-3 col-xs-12 text-right">
                    <ul class="meta-list list-unstyled">
                        <li class="post-time post_date date updated">
                            <span class="date">26</span>
                            <span class="month">Oct</span>
                        </li>
                        <li class="post-author"><a href="#">Sara Valdez</a></li>
                        <li class="post-comments-link">
                            Comments: <a href="##comment-area">8</a>
                        </li>
                    </ul><!--//meta-list-->
                </div><!--//meta-list-->
                <div class="content-wrapper col-md-10 col-sm-9 col-xs-12">
                    <figure class="figure">
                        <a href="#"><img class="img-responsive" src="/img/blog/blog-5.jpg" alt=""></a>
                    </figure>
                    <div class="content">
                        <div class="desc">
                            <p>Aliquam quis nibh id lorem fringilla scelerisque. Etiam euismod lectus at arcu ultrices suscipit. Ut eu mi in lectus viverra scelerisque. Nulla non commodo est. Aenean id tristique est. Pellentesque hendrerit tortor nulla, dapibus consequat orci convallis vitae. Vivamus at odio fermentum justo...</p>
                            <a class="read-more" href="#">Read more <i class="fa fa-long-arrow-right"></i></a>
                        </div><!--//desc-->
                    </div><!--//content-->
                </div><!--//content-wrapper-->
            </div><!--//row-->
        </article><!--//item-->
        <article class="item">
            <div class="row">
                <h3 class="post-title col-md-10 col-sm-9 col-xs-12 col-md-push-2 col-sm-push-3 col-xs-push-0"><a href="#">Design aenean vulputate eleifend tellus</a></h3>
                <div class="clearfix"></div>
                <div class="meta col-md-2 col-sm-3 col-xs-12 text-right">
                    <ul class="meta-list list-unstyled">
                        <li class="post-time post_date date updated">
                            <span class="date">12</span>
                            <span class="month">Sep</span>
                        </li>
                        <li class="post-author"><a href="#">Sara Valdez</a></li>
                        <li class="post-comments-link">
                            Comments: <a href="##comment-area">8</a>
                        </li>
                    </ul><!--//meta-list-->
                </div><!--//meta-list-->
                <div class="content-wrapper col-md-10 col-sm-9 col-xs-12">
                    <figure class="figure">
                        <a href="#"><img class="img-responsive" src="/img/blog/blog-6.jpg" alt=""></a>
                    </figure>
                    <div class="content">
                        <div class="desc">
                            <p>Aliquam quis nibh id lorem fringilla scelerisque. Etiam euismod lectus at arcu ultrices suscipit. Ut eu mi in lectus viverra scelerisque. Nulla non commodo est. Aenean id tristique est. Pellentesque hendrerit tortor nulla, dapibus consequat orci convallis vitae. Vivamus at odio fermentum justo...</p>
                            <a class="read-more" href="#">Read more <i class="fa fa-long-arrow-right"></i></a>
                        </div><!--//desc-->
                    </div><!--//content-->
                </div><!--//content-wrapper-->
            </div><!--//row-->
            <div class="pagination-container text-center">
                <ul class="pagination">
                    <li class="disabled"><a href="#">«</a></li>
                    <li class="active"><a href="#">1<span class="sr-only">(current)</span></a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li><a href="#">»</a></li>
                </ul><!--//pagination-->
            </div>
        </article><!--//item-->
    </div><!--//container-->
</section><!--//blog-list--> 