<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Versover'))->setSeparator(' &bull; ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico?v=1'))
                        ->prependStylesheet($this->basePath('css/app.css'))
                        ->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css')
                        ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css')
                        ->prependStylesheet('//fonts.googleapis.com/css?family=Merriweather+Sans:700,300italic,400italic,700italic,300,400')
                        ->prependStylesheet('//fonts.googleapis.com/css?family=Russo+One')
                        ->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800')
        ; ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile(('//oss.maxcdn.com/respond/1.4.2/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile(('//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div>
            <div class="header-wrapper">
                <!-- ******HEADER****** -->
                <header id="header" class="header navbar-fixed-top">
                    <div class="container">
                        <h1 class="logo">
                            <a href="<?= $this->url('home'); ?>"><span class="highlight">V</span>ersover</a>
                        </h1><!--//logo-->
                        <nav class="main-nav navbar-right" role="navigation">
                            <div class="navbar-header">
                                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button><!--//nav-toggle-->
                            </div><!--//navbar-header-->
                            <div id="navbar-collapse" class="navbar-collapse collapse">
                                <?= $this->navigation('navigation')->menu()->setULClass('nav navbar-nav'); ?><!--//nav-->
                            </div><!--//navabr-collapse-->
                        </nav><!--//main-nav-->
                    </div><!--//container-->
                </header><!--//header-->

            </div><!--//header-wrapper-->

            <?php echo $this->content; ?>
            <script>
                var path    = location.href.split('/').pop(),
                    place   = document.querySelector('.header-wrapper'),
                    replace = document.querySelector('.replace');
                switch (path) {
                    case 'work':
                        place.classList.add('header-wrapper-work');
                        break;
                    case 'about':
                        place.classList.add('header-wrapper-about');
                        break;
                    case 'blog':
                        place.classList.add('header-wrapper-blog-home');
                        break;
                    case 'contact':
                        place.classList.add('header-wrapper-contact');
                        break;
                    default:
                        place.classList.add('header-wrapper-home');
                }
                place.appendChild(replace).classList.remove('hide');
            </script>

            <!-- ******FOOTER****** -->
            <footer class="footer">
                <div class="footer-content">
                    <div class="container">
                        <div class="row">
                            <div class="footer-col col-xs-3 col-sm-offset-3 col-xs-offset-1 links-col">
                                <div class="footer-col-inner">
                                    <h3 class="sub-title"><?= $this->translate('Быстрые ссылки'); ?></h3>
                                    <ul class="list-unstyled">
                                        <li><a href="<?= $this->url('home'); ?>"><?= $this->translate('Главная'); ?></a></li>
                                        <li><a href="<?= $this->url('about'); ?>"><?= $this->translate('О нас'); ?></a></li>
                                        <li><a href="<?= $this->url('contact'); ?>"><?= $this->translate('Контакты'); ?></a></li>
                                        <li class="hide"><a href="<?= $this->url('blog'); ?>"><?= $this->translate('Blog'); ?></a></li>
                                    </ul>
                                </div><!--//footer-col-inner-->
                            </div><!--//foooter-col-->
                            <div class="footer-col col-xs-3 contact-col">
                                <div class="footer-col-inner">
                                    <h3 class="sub-title"><?= $this->translate('Всегда на связи'); ?></h3>
                                    <div class="row">
                                        <p><span class="fs1" aria-hidden="true" data-icon="&#x77;"></span><a href="tel:+380675623777">0675623777</a></p>
                                        <p><span class="fs1" aria-hidden="true" data-icon="&#xe010;"></span><a href="mailto:versoverteam@gmail.com">versoverteam@gmail.com</a></p>
                                        <p><span class="fs1" aria-hidden="true" data-icon="&#xe0a2;"></span><a href="skype:versover?chat">Versover</a></p>
                                    </div>
                                </div><!--//footer-col-inner-->
                            </div><!--//foooter-col-->
                        </div>
                    </div>
                </div><!--//footer-content-->
                <div class="bottom-bar">
                    <div class="container center">
                        <small class="copyright text-center">&copy; <a href="<?= $this->url('home'); ?>">Versover</a> <?= date('Y'); ?></small>
                    </div><!--//container-->
                </div><!--//bottom-bar-->
            </footer><!--//footer-->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <?php
        $script = $this->inlineScript();
        $script
            ->appendFile($this->basePath() . 'js/app.js');

        echo $script;
        ?>
    </body>
</html>
