<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Versover'))->setSeparator(' &bull; ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico?v=1'))
                        ->prependStylesheet($this->basePath('css/app.css'))
                        ->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css')
                        ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css')
                        ->prependStylesheet('//fonts.googleapis.com/css?family=Merriweather+Sans:700,300italic,400italic,700italic,300,400')
                        ->prependStylesheet('//fonts.googleapis.com/css?family=Russo+One')
                        ->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800')
        ; ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile(('//oss.maxcdn.com/respond/1.4.2/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile(('//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div>
            <div class="header-wrapper">
                <!-- ******HEADER****** -->
                <header id="header" class="header navbar-fixed-top">
                    <div class="container">
                        <h1 class="logo">
                            <a href="<?php echo $this->url('home'); ?>"><span class="highlight">V</span>ersover</a>
                        </h1><!--//logo-->
                        <nav class="main-nav navbar-right" role="navigation">
                            <div class="navbar-header">
                                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button><!--//nav-toggle-->
                            </div><!--//navbar-header-->
                            <div id="navbar-collapse" class="navbar-collapse collapse">
                                <?php echo $this->navigation('navigation')->menu()->setULClass('nav navbar-nav'); ?><!--//nav-->
                            </div><!--//navabr-collapse-->
                        </nav><!--//main-nav-->
                    </div><!--//container-->
                </header><!--//header-->

            </div><!--//header-wrapper-->

            <?php echo $this->content; ?>
            <script>
                var path    = location.href.split('/').pop(),
                    place   = document.querySelector('.header-wrapper'),
                    replace = document.querySelector('.replace');
                switch (path) {
                    case 'work':
                        place.classList.add('header-wrapper-work');
                        break;
                    case 'about':
                        place.classList.add('header-wrapper-about');
                        break;
                    case 'blog':
                        place.classList.add('header-wrapper-blog-home');
                        break;
                    case 'contact':
                        place.classList.add('header-wrapper-contact');
                        break;
                    default:
                        place.classList.add('header-wrapper-home');
                }
                place.appendChild(replace).classList.remove('hide');
            </script>

            <!-- ******FOOTER****** -->
            <footer class="footer">
                <div class="footer-content">
                    <div class="container">
                        <div class="row">
                            <div class="footer-col col-md-3 col-sm-4 links-col">
                                <div class="footer-col-inner">
                                    <h3 class="sub-title">Quick Links</h3>
                                    <ul class="list-unstyled">
                                        <li><a href="<?= $this->url('about'); ?>">About us</a></li>
                                        <li><a href="<?= $this->url('work'); ?>">Our work</a></li>
                                        <li><a href="<?= $this->url('contact'); ?>">Contact</a></li>
                                        <li><a href="<?= $this->url('blog'); ?>">Blog</a></li>
                                        <li><a href="#">Privacy policy</a></li>
                                        <li><a href="#">Terms &amp; Conditions</a></li>
                                    </ul>
                                </div><!--//footer-col-inner-->
                            </div><!--//foooter-col-->
                            <div class="footer-col col-md-6 col-sm-8 blog-col">
                                <div class="footer-col-inner">
                                    <h3 class="sub-title">Latest From Our Blog</h3>
                                    <div class="item">
                                        <figure class="figure">
                                            <img class="img-responsive" src="/img/blog/blog-tiny-thumb-1.jpg" alt="" />
                                        </figure>
                                        <div class="content">
                                            <h4 class="post-title"><a href="#">DevStudio helps XYZ launch</a></h4>
                                            <p class="intro">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sodales dolor ut ligula faucibus...</p>
                                            <ul class="meta list-inline">
                                                <li>18 Feb 2015</li>
                                                <li>James Lee</li>
                                            </ul>
                                        </div><!--//content-->
                                    </div>
                                    <div class="item">
                                        <figure class="figure">
                                            <img class="img-responsive" src="/img/blog/blog-tiny-thumb-2.jpg" alt="" />
                                        </figure>
                                        <div class="content">
                                            <h4 class="post-title"><a href="#">devAid - Free Bootstrap Theme</a></h4>
                                            <p class="intro">Mauris libero leo, dapibus a congue ut, mollis sed nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempus augue nec nulla ultricies...</p>
                                            <ul class="meta list-inline">
                                                <li>21 Dec 2014</li>
                                                <li>Vincent Fowler</li>
                                            </ul>
                                        </div><!--//content-->
                                    </div>
                                </div><!--//footer-col-inner-->
                            </div><!--//foooter-col-->
                            <div class="footer-col col-md-3 col-sm-12 contact-col">
                                <div class="footer-col-inner">
                                    <h3 class="sub-title">Get In Touch</h3>
                                    <p class="intro"></p>
                                    <div class="row">
                                        <p class="adr clearfix col-md-12 col-sm-4">
                                            <span class="fs1" aria-hidden="true" data-icon="&#xe01d;"></span>
                                    <span class="adr-group">
                                        <span class="street-address">56 College Green Road</span><br />
                                        <span class="city">Bristol</span><br />
                                        <span class="postal-code">BS1 XR18</span><br />
                                        <span class="country-name">UK</span>
                                    </span>
                                        </p>
                                        <p class="tel col-md-12 col-sm-4"><span class="fs1" aria-hidden="true" data-icon="&#x77;"></span><a href="tel:+08001234567">0800 123 4567</a></p>
                                        <p class="email col-md-12 col-sm-4"><span class="fs1" aria-hidden="true" data-icon="&#xe010;"></span><a href="#">hello@yourdevstudio.com</a></p>
                                    </div>
                                </div><!--//footer-col-inner-->
                            </div><!--//foooter-col-->
                        </div>
                    </div>
                </div><!--//footer-content-->
                <div class="bottom-bar">
                    <div class="container center">
                        <ul class="social-icons list-inline">
                            <li><a href="https://twitter.com/3rdwave_themes"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="https://www.facebook.com/3rdwavethemes"><i class="fa fa-instagram"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li class="last"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                        <small class="copyright text-center">&copy; <a href="<?= $this->url('home'); ?>">Versover</a> <?php echo date('Y'); ?></small>
                    </div><!--//container-->
                </div><!--//bottom-bar-->
            </footer><!--//footer-->

            <!-- Contact Modal -->
            <div class="modal modal-contact" id="modal-contact" tabindex="-1" role="dialog" aria-labelledby="contactModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 id="contactModalLabel" class="modal-title text-center">Start your project today</h4>
                            <p class="intro text-center">Lorem ipsum dolor sit amet consectetur adipiscing elit laoreet tortor consequat nisi scelerisque commodo etiam justo sapien.</p>
                        </div>
                        <div class="modal-body">
                            <ul class="contact-info list-inline text-center">
                                <li class="tel"><span class="fs1" aria-hidden="true" data-icon="&#x77;"></span><br /> <a href="+0800123456">0800 123 4567</a></li>
                                <li class="email"><span class="fs1" aria-hidden="true" data-icon="&#xe010;"></span><br /> <a href="#">hello@yourdevstudio.com</a></li>
                            </ul>
                            <form id="contact-form" class="contact-form" method="post" action="#">
                                <div class="row text-center">
                                    <div class="contact-form-inner">
                                        <div class="row">

                                            <div class="col-md-6 col-sm-6 col-xs-12 form-group">
                                                <label class="sr-only" for="cname">Your name</label>
                                                <input type="text" class="form-control" id="cname" name="name" placeholder="Your name" minlength="2" required>
                                            </div>
                                            <div class="col-md-6 col-sm-6 col-xs-12 form-group">
                                                <label class="sr-only" for="cemail">Email address</label>
                                                <input type="email" class="form-control" id="cemail" name="email" placeholder="Your email address" required>
                                            </div>
                                            <div class="col-md-12 col-sm-12 col-xs-12 form-group">
                                                <label class="sr-only" for="cmessage">Your message</label>
                                                <textarea class="form-control" id="cmessage" name="message" placeholder="Enter your message" rows="12" required></textarea>
                                            </div>
                                            <div class="col-md-12 col-sm-12 col-xs-12 form-group">
                                                <button type="submit" class="btn btn-block btn-cta btn-cta-primary">Send Message</button>
                                            </div>
                                        </div><!--//row-->
                                    </div>
                                </div><!--//row-->
                                <div id="form-messages"></div>
                            </form><!--//contact-form-->
                        </div><!--//modal-body-->
                    </div><!--//modal-content-->
                </div><!--//modal-dialog-->
            </div><!--//modal-->
        </div> <!-- /container -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <?php
        $script = $this->inlineScript();
        $script
            ->appendFile($this->basePath() . 'js/app.js');

        echo $script;
        ?>
    </body>
</html>
