<?php
$title = 'Главная';
$this->headTitle($title);
?>
<div class="replace hide">
    <div class="bg-slider-wrapper">
        <div id="bg-slider" class="flexslider bg-slider">
            <ul class="slides">
                <li class="slide slide-1"></li>
                <li class="slide slide-2"></li>
                <li class="slide slide-3"></li>
            </ul>
        </div>
    </div><!--//bg-slider-wrapper-->
    <section id="home-promo" class="home-promo section">
        <div class="container text-center">
            <div class="title">
                <span class="upper filler">Мы создаем</span><br><br>
                <span class="middle filler">Веб-приложения</span><br>
                <span class="bottom filler">для стартапов и организаций</span>
            </div>
            <button class="btn btn-cta btn-cta-primary" type="button" data-toggle="modal" data-target="#modal-contact" data-backdrop="static">Обратитесь к нам</button>
        </div><!--//container-->
    </section><!--//promo-->
</div>
<!-- ******Why Section****** -->
<section id="who" class="who section">
    <div class="container text-center">
        <h2 class="title text-center">Кто мы</h2>
        <p class="intro text-center"><strong class="highlight">Versover</strong> - веб-разработчики с полным спектром услуг, специализирующаяся на PHP и Zend Framework.</p>
        <div class="row benefits text-center">
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/PHP" target="_blank" class="brand-logo php"></a>
                    <h3 class="sub-title">PHP</h3>
                    <div class="desc">
                        <p>Один из лидеров среди языков, применяющихся для создания динамических веб-приложений.</p>
                    </div>
                </div>
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12 sm-break">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/Zend_Framework" target="_blank" class="brand-logo zendframework"></a>
                    <h3 class="sub-title">Zend Framework</h3>
                    <div class="desc">
                        <p>Один из наиболее мощных программных каркасов для разработки веб-приложений.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/MySQL" target="_blank" class="brand-logo mysql"></a>
                    <h3 class="sub-title">MySQL</h3>
                    <div class="desc">
                        <p>Свободная реляционная система управления базами данных. MySQL является решением для малых и средних приложений.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/PostgreSQL" target="_blank" class="brand-logo postgresql"></a>
                    <h3 class="sub-title">PostgreSQL</h3>
                    <div class="desc">
                        <p>Объектно-реляционная система управления базами данных. Обладает богатым функционалом. Подходит для средних и крупных проектов.</p>
                    </div>
                </div>
            </div><!--//item-->
        </div><!--//row-->
        <div class="row benefits text-center">
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/SQLite" target="_blank" class="brand-logo sqlite"></a>
                    <h3 class="sub-title">SQLite</h3>
                    <div class="desc">
                        <p>Компактная встраиваемая реляционная база данных. Хорошее решение для небольших проектов.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12 sm-break">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/JavaScript" target="_blank" class="brand-logo javascript"></a>
                    <h3 class="sub-title">JavaScript</h3>
                    <div class="desc">
                        <p>Наиболее широкое применение находит в браузерах как язык сценариев для придания интерактивности веб-страницам.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/JQuery" target="_blank" class="brand-logo jquery"></a>
                    <h3 class="sub-title">jQuery</h3>
                    <div class="desc">
                        <p>Популярная JavaScript библиотека, которая обладает большим набором возможностей для создания великолепных визуальных эффектов и не только.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/Ajax_(programming)" target="_blank" class="brand-logo ajax"></a>
                    <h3 class="sub-title">AJAX</h3>
                    <div class="desc">
                        <p>Подход к построению интерактивных пользовательских веб-приложений, заключающийся в «фоновом» обмене данными браузера с веб-сервером.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
        </div><!--//row-->
        <div class="row benefits text-center">
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/HTML5" target="_blank" class="brand-logo html5"></a>
                    <h3 class="sub-title">HTML5</h3>
                    <div class="desc">
                        <p>Язык разметки документов в интернете.</p>
                    </div>
                </div>
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12 sm-break">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/Cascading_Style_Sheets" target="_blank" class="brand-logo css3"></a>
                    <h3 class="sub-title">CSS3</h3>
                    <div class="desc">
                        <p>Язык, который используется для описания внешнего вида документа.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/Bootstrap_(front-end_framework)" target="_blank" class="brand-logo bootstrap"></a>
                    <h3 class="sub-title">Bootstrap</h3>
                    <div class="desc">
                        <p>Набор инструментов для создания сайтов и веб-приложений.
                            Включает в себя: HTML и CSS шаблоны, оформления для типографики, веб-формы, кнопки, метки, блоки навигации и прочие компоненты веб-интерфейсов, включая JavaScript расширения.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/XML" target="_blank" class="brand-logo xml"></a>
                    <h3 class="sub-title">XML</h3>
                    <div class="desc">
                        <p>eXtensible Markup Language — расширяемый язык разметки. Формат удобный для создания и обработки документов программами и одновременно удобный для чтения человеком.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
        </div><!--//row-->
        <div class="row benefits text-center">
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <a href="#" target="_blank" class="brand-logo json"></a>
                    <h3 class="sub-title">JSON</h3>
                    <div class="desc">
                        <p>Текстовый формат обмена данными, в настоящее время очень популярен в веб.</p>
                    </div>
                </div>
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12 sm-break">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/JSON" target="_blank" class="brand-logo elasticsearch"></a>
                    <h3 class="sub-title">ElasticSearch</h3>
                    <div class="desc">
                        <p>Поисковый сервер. Обеспечивает распределенный, высокоскоростной механизм полнотекстового поиска, веб-интерфейс и схему JSON документов.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <a href="http://gulpjs.com/" target="_blank" class="brand-logo gulp"></a>
                    <h3 class="sub-title">Gulp</h3>
                    <div class="desc">
                        <p>Современный инструмент для автоматизация процесса разработки.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/Git_(software)" target="_blank" class="brand-logo git"></a>
                    <h3 class="sub-title">Git</h3>
                    <div class="desc">
                        <p>Система для управления версиями.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
        </div><!--//row-->
        <div class="row benefits text-center">
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/Composer_(software)" target="_blank" class="brand-logo composer"></a>
                    <h3 class="sub-title">Composer</h3>
                    <div class="desc">
                        <p>Пакетный менеджер уровня приложений для языка программирования PHP, который предоставляет средства по управлению зависимостями в PHP-приложении.</p>
                    </div>
                </div>
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12 sm-break">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/Npm_(software)" target="_blank" class="brand-logo npm"></a>
                    <h3 class="sub-title">NPM</h3>
                    <div class="desc">
                        <p>Пакетный менеджер для языка JavaScript.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <a href="http://bower.io/" target="_blank" class="brand-logo bower"></a>
                    <h3 class="sub-title">Bower</h3>
                    <div class="desc">
                        <p>Система управления пакетами для программирования на стороне клиента.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/Vagrant_(software)" target="_blank" class="brand-logo vagrant"></a>
                    <h3 class="sub-title">Vagrant</h3>
                    <div class="desc">
                        <p>Программное обеспечение для создания и конфигурирования виртуальной среды разработки.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
        </div><!--//row-->
        <div class="row benefits text-center">
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/Web_scraping" target="_blank" class="brand-logo web-scraper"></a>
                    <h3 class="sub-title">Web-scraping</h3>
                    <div class="desc">
                        <p>Программное обеспечение для извлечения информации из веб-сайтов.</p>
                    </div>
                </div>
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12 sm-break">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/PayPal" target="_blank" class="brand-logo paypal"></a>
                    <h3 class="sub-title">PayPal</h3>
                    <div class="desc">
                        <p>Реализация PHP системы для работы с крупнейшей дебетовой электронная платежной системой.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/Doctrine_(PHP)" target="_blank" class="brand-logo doctrine"></a>
                    <h3 class="sub-title">Doctrine</h3>
                    <div class="desc">
                        <p>Объектно-реляционный проектор (ORM) для PHP. Одной из ключевых возможностей Doctrine является запись запросов к БД на собственном объектно-ориентированном диалекте SQL.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <a href="https://en.wikipedia.org/wiki/Representational_state_transfer" target="_blank" class="brand-logo rest"></a>
                    <h3 class="sub-title">REST</h3>
                    <div class="desc">
                        <p>Representational State Transfer. Метод взаимодействия компонентов распределенного приложения в сети Интернет.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
        </div><!--//row-->
        <a class="btn btn-cta btn-cta-secondary" href="<?= $this->url('about'); ?>">Больше о нас</a>
    </div><!--//container-->
</section><!--//who-->

<!-- ******CTA Section****** -->
<section id="cta-section" class="cta-section section text-center home-cta-section">
    <div class="container">
        <h2 class="title"><span class="filler">Хотите быстро связаться с нами?</span></h2>
        <p class="phone contact-info">
            <span class="intro filler">Вы в одном телефонном звонке от этого</span><br>
            <span class="info filler"><a href="tel:+380675623777">0675623777</a></span>
        </p><!--//phone-->
        <p class="email contact-info">
            <span class="intro filler">Вы так же можете отправить email</span><br>
            <span class="info filler"><a href="mailto:versoverteam@gmail.com">versoverteam@gmail.com</a></span>
        </p><!--//phone-->
        <p class="skype contact-info">
            <span class="intro filler">Или Skype</span><br>
            <span class="info filler"><a href="skype:versover?chat">Versover</a></span>
        </p><!--//skype-->
    </div><!--//container-->
</section><!--//cta-section-->

<!-- Contact Modal -->
<div class="modal modal-contact" id="modal-contact" tabindex="-1" role="dialog" aria-labelledby="contactModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 id="contactModalLabel" class="modal-title text-center">Начните проект сегодня</h4>
                <p class="intro text-center">Если у вас есть предложение, вопрос - смело пишите нам - мы ответим Вам в ближайшее время!</p>
            </div>
            <div class="modal-body">
                <ul class="contact-info list-inline text-center">
                    <li class="tel"><span class="fs1" aria-hidden="true" data-icon="&#x77;"></span><br> <a href="tel:+380675623777">0675623777</a></li>
                    <li class="email"><span class="fs1" aria-hidden="true" data-icon="&#xe010;"></span><br> <a href="mailto:versoverteam@gmail.com">versoverteam@gmail.com</a></li>
                    <li class="skype-icon"><span class="fs1" aria-hidden="true" data-icon="&#xe0a2;"></span><br> <a href="skype:versover?chat">Versover</a></li>
                </ul>
                <form id="contact-form" class="contact-form" method="post" action="<?= $this->url('contact', ['action' => 'send']); ?>">
                    <div class="row text-center">
                        <div class="contact-form-inner">
                            <div class="row">
                                <div class="col-md-6 col-sm-6 col-xs-12 form-group">
                                    <label class="sr-only" for="cname">Ваше имя</label>
                                    <input type="text" class="form-control" id="cname" name="name" placeholder="Ваше имя" minlength="2" required>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-12 form-group">
                                    <label class="sr-only" for="cemail">Ваш email</label>
                                    <input type="email" class="form-control" id="cemail" name="email" placeholder="Ваш email" required>
                                </div>
                                <div class="col-md-12 col-sm-12 col-xs-12 form-group">
                                    <label class="sr-only" for="csubject">Тема</label>
                                    <input type="text" class="form-control" id="csubject" name="subject" placeholder="Тема" required>
                                </div>
                                <div class="col-md-12 col-sm-12 col-xs-12 form-group">
                                    <label class="sr-only" for="cmessage">Ваше сообщение</label>
                                    <textarea class="form-control" id="cmessage" name="message" placeholder="Ваше сообщение" rows="12" required></textarea>
                                </div>
                                <div class="col-md-12 col-sm-12 col-xs-12 form-group">
                                    <button type="submit" class="btn btn-block btn-cta btn-cta-primary sbm-btn">Отправить сообщение</button>
                                </div>
                            </div><!--//row-->
                        </div>
                    </div><!--//row-->
                    <div id="form-messages"></div>
                </form><!--//contact-form-->
            </div><!--//modal-body-->
        </div><!--//modal-content-->
    </div><!--//modal-dialog-->
</div><!--//modal-->