<?php
$title = 'Главная';
$this->headTitle($title);
?>
<div class="replace hide">
    <div class="bg-slider-wrapper">
        <div id="bg-slider" class="flexslider bg-slider">
            <ul class="slides">
                <li class="slide slide-1"></li>
                <li class="slide slide-2"></li>
                <li class="slide slide-3"></li>
            </ul>
        </div>
    </div><!--//bg-slider-wrapper-->
    <section id="home-promo" class="home-promo section">
        <div class="container text-center">
            <h2 class="title">
                <span class="upper">Мы создаем</span>
                <span class="middle">Веб-приложения</span>
                <span class="bottom">для стартапов и организаций</span>
            </h2>
            <button class="btn btn-cta btn-cta-primary" type="button" data-toggle="modal" data-target="#modal-contact" data-backdrop="static">Обратитесь к нам</button>
        </div><!--//container-->
    </section><!--//promo-->
</div>
<!-- ******Why Section****** -->
<section id="who" class="who section">
    <div class="container text-center">
        <h2 class="title text-center">Кто мы</h2>
        <p class="intro text-center"><strong class="highlight">Versover</strong> - веб-разработчики с полным спектром услуг, специализирующаяся на PHP и Zend Framework.</p>
        <div class="row benefits text-center">
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="brand-logo php"></div>
                    <h3 class="sub-title">PHP</h3>
                    <div class="desc">
                        <p>Один из лидеров среди языков, применяющихся для создания динамических веб-приложений.</p>
                    </div>
                </div>
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12 sm-break">
                <div class="item-inner">
                    <div class="brand-logo zendframework"></div>
                    <h3 class="sub-title">Zend Framework</h3>
                    <div class="desc">
                        <p>Один из наиболее мощных программных каркасов для разработки веб-приложений.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="brand-logo mysql"></div>
                    <h3 class="sub-title">MySQL</h3>
                    <div class="desc">
                        <p>Свободная реляционная система управления базами данных. MySQL является решением для малых и средних приложений.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="brand-logo javascript"></div>
                    <h3 class="sub-title">SQLite</h3>
                    <div class="desc">
                        <p>Компактная встраиваемая реляционная база данных. Хорошее решение для небольших проектов.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
        </div><!--//row-->
        <div class="row benefits text-center">
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="brand-logo jquery"></div>
                    <h3 class="sub-title">PostgreSQL</h3>
                    <div class="desc">
                        <p>Объектно-реляционная система управления базами данных. Обладает богатым функционалом. Подходит для средних и крупных проктов.</p>
                    </div>
                </div>
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12 sm-break">
                <div class="item-inner">
                    <div class="brand-logo ajax"></div>
                    <h3 class="sub-title">JavaScript</h3>
                    <div class="desc">
                        <p>Наиболее широкое применение находит в браузерах как язык сценариев для придания интерактивности веб-страницам.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="brand-logo sqlite"></div>
                    <h3 class="sub-title">jQuery</h3>
                    <div class="desc">
                        <p>Поплуярная JavaScript библиотека, которая обладает большим набором возможностей для создания великолепных визуальных эффектов и не только.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="brand-logo postgresql"></div>
                    <h3 class="sub-title">AJAX</h3>
                    <div class="desc">
                        <p>Gодход к построению интерактивных пользовательских веб-приложений, заключающийся в «фоновом» обмене данными браузера с веб-сервером.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
        </div><!--//row-->
        <div class="row benefits text-center">
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="brand-logo html5"></div>
                    <h3 class="sub-title">HTML5</h3>
                    <div class="desc">
                        <p>Язык разметки документов в интернете.</p>
                    </div>
                </div>
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12 sm-break">
                <div class="item-inner">
                    <div class="brand-logo css3"></div>
                    <h3 class="sub-title">CSS3</h3>
                    <div class="desc">
                        <p>Язык разметки, который используется для описания внешнего вида документа.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="brand-logo bootstrap"></div>
                    <h3 class="sub-title">Bootstrap</h3>
                    <div class="desc">
                        <p>Набор инструментов для создания сайтов и веб-приложений.
                            Включает в себя HTML и CSS шаблоны оформления для типографики, веб-форм, кнопок, меток, блоков навигации и прочих компонентов веб-интерфейсов, включая JavaScript расширения.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="brand-logo xml"></div>
                    <h3 class="sub-title">XML</h3>
                    <div class="desc">
                        <p>eXtensible Markup Language — расширяемый язык разметки. Формат удобный для создания и обработки документов программами и одновременно удобный для чтения.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
        </div><!--//row-->
        <div class="row benefits text-center">
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="brand-logo json"></div>
                    <h3 class="sub-title">JSON</h3>
                    <div class="desc">
                        <p>Текстовый формат обмена данными, в настоящее время очень популярен в веб.</p>
                    </div>
                </div>
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12 sm-break">
                <div class="item-inner">
                    <div class="brand-logo elasticsearch"></div>
                    <h3 class="sub-title">ElasticSearch</h3>
                    <div class="desc">
                        <p>Поисковый сервер. Обеспечивает распределенный, высокоскоростной механизм полнотекстового поиска, веб-интерфейс и схему JSON документов.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="brand-logo gulp"></div>
                    <h3 class="sub-title">Gulp</h3>
                    <div class="desc">
                        <p>Современный инструмент для автоматизация процесса разработки.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="brand-logo git"></div>
                    <h3 class="sub-title">Git</h3>
                    <div class="desc">
                        <p>Система для управления версиями.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
        </div><!--//row-->
        <div class="row benefits text-center">
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="brand-logo npm"></div>
                    <h3 class="sub-title">Composer</h3>
                    <div class="desc">
                        <p>Пакетный менеджер уровня приложений для языка программирования PHP, который предоставляет средства по управлению зависимостями в PHP-приложении.</p>
                    </div>
                </div>
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12 sm-break">
                <div class="item-inner">
                    <div class="brand-logo bower"></div>
                    <h3 class="sub-title">NPM</h3>
                    <div class="desc">
                        <p>Пакетный менеджер для языка JavaScript.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="brand-logo vagrant"></div>
                    <h3 class="sub-title">Bower</h3>
                    <div class="desc">
                        <p>Система управления пакетами для программирования на стороне клиента.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="brand-logo paypal"></div>
                    <h3 class="sub-title">Vagrant</h3>
                    <div class="desc">
                        <p>Программное обеспечение для создания и конфигурирования виртуальной среды разработки.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
        </div><!--//row-->
        <div class="row benefits text-center">
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="brand-logo web-scraper"></div>
                    <h3 class="sub-title">Web-scraping</h3>
                    <div class="desc">
                        <p>Программное обеспечение для обеспечение извлечения информации из веб-сайтов.</p>
                    </div>
                </div>
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12 sm-break">
                <div class="item-inner">
                    <div class="brand-logo bower"></div>
                    <h3 class="sub-title">PayPal</h3>
                    <div class="desc">
                        <p>Реализация PHP ситсемы для работы с крупнейшей дебетовой электронная платежной системой.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="brand-logo vagrant"></div>
                    <h3 class="sub-title">Doctrine</h3>
                    <div class="desc">
                        <p>Объектно-реляционный проектор (ORM) для PHP. Одной из ключевых возможностей Doctrine является запись запросов к БД на собственном объектно-ориентированном диалекте SQL.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
            <div class="item col-md-3 col-sm-6 col-xs-12">
                <div class="item-inner">
                    <div class="brand-logo paypal"></div>
                    <h3 class="sub-title">REST</h3>
                    <div class="desc">
                        <p>Representational State Transfer. Метод взаимодействия компонентов распределённого приложения в сети Интернет.</p>
                    </div>
                </div><!--//item-inner-->
            </div><!--//item-->
        </div><!--//row-->
        <a class="btn btn-cta btn-cta-secondary" href="<?= $this->url('about'); ?>">Больше о нас</a>
    </div><!--//container-->
</section><!--//who-->

<!-- ******CTA Section****** -->
<section id="cta-section" class="cta-section section text-center home-cta-section">
    <div class="container">
        <h2 class="title">Хотите быстро связатся с нами?</h2>
        <p class="phone contact-info">
            <span class="intro">Вы в одном телефонном звонке от этого</span>
            <span class="info"><a href="tel:+380675623777">0675623777</a></span>
        </p><!--//phone-->
        <p class="email contact-info">
            <span class="intro">Вы так же можете отправить email</span>
            <span class="info"><a href="mailto:versover@gmail.com">versover@gmail.com</a></span>
        </p><!--//phone-->
    </div><!--//container-->
</section><!--//cta-section-->